xcopy ..\RsoCS\Balance\*.cs .\Assets\RsoCS\Balance\ /Y
xcopy ..\RsoCS\Balance_LC\*.cs .\Assets\RsoCS\Balance_LC\ /Y
xcopy ..\RsoCS\Balance_RR\*.cs .\Assets\RsoCS\Balance_RR\ /Y
xcopy ..\RsoCS\Base\*.cs .\Assets\RsoCS\Base\ /Y
xcopy ..\RsoCS\Core\*.cs .\Assets\RsoCS\Core\ /Y
xcopy ..\RsoCS\Crypto\*.cs .\Assets\RsoCS\Crypto\ /Y
xcopy ..\RsoCS\Game\*.cs .\Assets\RsoCS\Game\ /Y
xcopy ..\RsoCS\GameUtil\*.cs .\Assets\RsoCS\GameUtil\ /Y
xcopy ..\RsoCS\Google\*.cs .\Assets\RsoCS\Google\ /Y
xcopy ..\RsoCS\Http\*.cs .\Assets\RsoCS\Http\ /Y
xcopy ..\RsoCS\Math\*.cs .\Assets\RsoCS\Math\ /Y
xcopy ..\RsoCS\Mobile\*.cs .\Assets\RsoCS\Mobile\ /Y
xcopy ..\RsoCS\Monitor\*.cs .\Assets\RsoCS\Monitor\ /Y
xcopy ..\RsoCS\Net\*.cs .\Assets\RsoCS\Net\ /Y
xcopy ..\RsoCS\Physics\*.cs .\Assets\RsoCS\Physics\ /Y
xcopy ..\RsoCS\Proto\*.cs .\Assets\RsoCS\Proto\ /Y
